# Generated by Django 5.1.7 on 2025-03-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_demo_app", "0004_usertextdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertextdata",
            name="name",
            field=models.CharField(default="Default Name", max_length=100),
            preserve_default=False,
        ),
    ]
