name: Django CI

on:
  push:
    paths:
      - '**/*.py'
      - 'requirements.txt'
  pull_request:
    paths:
      - '**/*.py'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox xvfb

        GECKO_V=0.33.0
        wget -q "https://github.com/mozilla/geckodriver/releases/download/v${GECKO_V}/geckodriver-v${GECKO_V}-linux64.tar.gz"
        tar xzf geckodriver-*.tar.gz
        sudo mv geckodriver /usr/local/bin/

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium
        pip install coverage flake8 black

    - name: Lint with flake8
      run: |
        flake8 .

    - name: Check style with black
      run: |
        black --check .

    - name: Run unit tests with coverage
      run: |
        MANAGE_PATH=$(find . -type f -name "manage.py" | head -n 1)
        if [ -z "$MANAGE_PATH" ]; then
          echo "manage.py not found"
          exit 1
        fi
        cd $(dirname "$MANAGE_PATH")
        coverage run manage.py test
        coverage report --fail-under=80
