# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "*" ]
    paths:
      - '**/*.js'
  pull_request:
    branches: [ "*" ]
    paths:
      - '**/*.js'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Run CI tasks in all Node.js projects
      run: |
        echo "Searching for all package.json files"
        for dir in $(find . -name package.json -not -path "*/node_modules/*" -exec dirname {} \;); do
          echo "Found project at $dir"
          cd $dir

          echo "Installing dependencies"
          npm install

          echo "Ensuring patch-package is available"
          npm install patch-package --save-dev

          echo "Lint"
          npm run lint || echo "Lint failed, but continuing..."

          echo "Tests (if defined)"
          npm test --if-present || echo "Tests failed, but continuing..."

          echo "Done with $dir"
          cd -
        done
